- README.md
> timeline added

- .github/workflows/test.yml
"Added GitHub Actions test workflow"
> added CI/CD

- client/package-lock.json
- client/package.json
- client/src/components/signUp.tsx
- client/src/graphql/mutations.tsx
- package-lock.json
- package.json
Created a SignUp page, for users to sign up, with an email, username and password
> Adding SignUp page

- .github/workflows/test.yml
- package.json
- server/jest.config.js
- server/jest.config.mjs
- server/package.json
- Modified package.json:
- Ensured 'start' runs the compiled dist/index.js for Render.
- Added 'engines' to force Node.js 18.x for compatibility.
- Verified 'build' command compiles TypeScript using tsc.
- Jest Testing Setup:
- Added jest.config.js to enable TypeScript-based testing.
- Installed Jest and ts-jest for unit testing.
- Updated package.json to include 'test' script.
- Preparation for Render Deployment:
- Ensured backend is fully optimized before deployment.
- Updated scripts to support CI/CD in future updates."
> Updated package.json for Render deployment

- .github/workflows/test.yml
- server/__tests__/sample.test.ts
- server/jest.config.ts
- server/package-lock.json
- server/package.json
added test, so we can push with ease
> Added GitHub Actions workflow for Jest tests

- server/package-lock.json
- server/package.json
> render first deployment

- package-lock.json
- package.json
> root folder's package.json also edited

- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
- server/src/graphql/resolvers.ts
- server/src/graphql/typeDefs.ts
- server/src/models/User.ts
- generateQR Mutation: Creates a QR code linked to a payment request.
- scanQR Mutation: Processes the transaction when a QR code is scanned.
- Wallet Updates: Deducts funds from the payer and credits them to the recipient.
- Transaction Logging: Stores QR code transactions and marks them as pending or completed.
- Database Migration: Ensured all transactions now include a qrCode field.
✅ Tested in Postman and verified in MongoDB Atlas.
> Implement QR Code Payment System

- client/src/components/navbar.tsx
- client/utils/auth.ts
Created a Navbar component 
Added a 'Auth.tsx' file for login logic
> Added Navbar

- client/package-lock.json
- client/package.json
- client/src/components/signIn.tsx
- client/src/components/signUp.tsx
- server/src/app.ts
1.) npm install jwt-decode at the frontend
2.) import path in the server
3.) if (process.env.NODE_ENV === "production") {
app.use(express.static(path.join(__dirname, "../client/build"))); // 🔹 Serve React frontend
app.get("*", (req, res) => {
res.sendFile(path.resolve(__dirname, "../client/build", "index.html"));
});
}
> updated CORS and added file path

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- README.md
- client/package.json
- client/src/components/transactions.tsx
- client/src/main.tsx
- package.json
- server/package.json
Added Readme File.
Added build test and deploy test.
No errors on the main branch now:
Also what changed during a force push: (I apologise)
1.) Auth.ts (client need to change a code) TOKEN handling.
2.) App.tsx (routed all path to components) - just need to force route it because render showing error if not connected
3.)Arrange the order of code in app.ts (server side) - I put Apollo server first before frontend production.
4.) transaction.tsx is just a draft and not a done well, for some reason it's one of the errors of render last night.
5.) added mutation code in mutation.tsx
> added test to secure CORS + ReadME

- client/public/bread.svg
- client/src/App.tsx
- client/src/components/navbar.tsx
- client/src/components/signIn.tsx
- client/src/components/signUp.tsx
- client/src/pages/Login.tsx
- client/src/pages/SignUp.tsx
- client/tailwind.config.js
- slight code changes to Navbar/Login/SignUp for styling purposes outside of tailwind classes to match the FIGMA designs
- added tailwind classes for login
- added tailwind class for signup
> UI styling

- client/src/components/navbar.tsx
- client/src/utils/auth.ts
- added window.addEventListener to navbar
- make sure the listner was pulled @ auth.ts and named the event as (authChange)
:)
> missing navigational j.s effect

- client/package-lock.json
- client/package.json
- client/src/App.tsx
- client/src/components/Chatbot.tsx
- client/src/graphql/queries.tsx
- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
- server/src/config/chatbotInstructions.ts
- server/src/graphql/resolvers.ts
- server/src/graphql/typeDefs.ts
DO NOT MERGE unless all have read this description: 
First off please update your .env file. (the update is posted @ slack) @shareefevans , @lachieMiles 
second, I made it work, up to you @shareefevans and @lachieMiles if you wanted to improve the style.
Third, I have tested this many times and it works locally, I have already updated the environment in render to accomodate this push.
- Integrated AI chatbot with Google Gemini for dynamic responses
- Allowed guest users to access chatbot without login
- Fixed token authentication issues for logged-out users
- Improved chatbot UI with fintech-styled floating icon & better dialogue box
- Updated backend resolver to ensure `userId` is optional
- Deployed and tested chatbot functionality successfully
> Added dynamic AI chatbot with guest support (UPDATE Local server .env file before/after merge)

- client/package-lock.json
- client/package.json
- client/src/App.tsx
- client/src/components/QrCodeModal.tsx
- client/src/components/QrCodeScanner.tsx
- client/src/components/dashboard.tsx
- client/src/pages/SignUp.tsx
- client/tailwind.config.js
- package-lock.json
- package.json
- created QR code component
- created QR code scanner component
- trigger points are deposit and payments for the above modals
- updated the UI + tailwindcss + App.tsx adding custom classes in order to make the site as responsive as possible on smaller screens
- updated signup with some new text
- updated the dashboard to send userID props to both the QRcode and QRcode scanner + passed the components through
NOTE: still left is to reconnect the 'get started' button if users dont have an account
> Trigger QR code + QR scanner

- client/package-lock.json
> push installed modules

- client/src/components/QrCodeModal.tsx
- client/src/components/QrCodeScanner.tsx
put stricter code in use effect
make sure ID is parse
> Qr code bug/feature

- server/src/graphql/resolvers.ts
Transactions will no longer stay in "pending".
Transaction times will be shown in AEST (Melbourne Time).
Data will now include a status field for clarity.
> changed transaction time to AEST and update transaction status

- client/package-lock.json
- client/src/components/navbar.tsx
- client/src/components/signIn.tsx
- client/src/components/signUp.tsx
- created an account link for when users accidentally create new account but have an existing account
- re routed the `create account` in the navbar
> button routing

- client/src/apollo/client.ts
- client/src/components/QrCodeScanner.tsx
- client/src/components/TransactionHistory.tsx
- client/src/components/dashboard.tsx
- server/src/graphql/resolvers.ts
I think we have a MONGODB error here, ill debug this, for now transaction history is updated .
> fixed transaction display

- client/src/apollo/client.ts
- client/src/components/TransactionHistory.tsx
- client/src/components/dashboard.tsx
- client/src/components/navbar.tsx
- client/src/graphql/mutations.tsx
- client/src/graphql/queries.tsx
- client/src/utils/auth.ts
- server/src/graphql/resolvers.ts
- server/src/graphql/typeDefs.ts
- server/src/models/Transaction.ts
The error was, our app doesnt really know how to get data from front end,. the money we have there were from insomia which was injected via back end, therefore a big code overhaul is needed to teach the front end to create data for our backend to process.
This is tested locally, and works like a smooth butterfly
> now scanning update realtime transactions

- client/src/components/BankDepositModal.tsx
- client/src/components/PaymentOptionsModal.tsx
- client/src/components/QrCodeScanner.tsx
- client/src/components/dashboard.tsx
created 2 files
✔️ BankDepositModal.tsx and
✔️ PaymentOptionModal.tsx
then 
I added it on the dashboard (literally just squash it in between buttons) nothing was changed.
> modal option for payment button

- README.md
Updated test command to 'npm RUN test'
> fixed testing command
